### ISSUE TITLE
curl VS file_get_contents VS Guzzle

### ISSUE THREAD

**Issue by gtrias** [ciricihq/oc-client-php#1]
Choosing the way we'll make the HTTP requests.

**Comment by gtrias** [comment]
ping @elboletaire

**Comment by elboletaire** [comment]
Let's study it a bit further https://github.com/lorien/awesome-web-scraping/blob/master/php.md#network

**Comment by elboletaire** [comment]
Between curl/file_get_contents and a library like Guzzle, I'd choose the library. Guzzle internally uses curl, which works perfect and we've seen that is less error-prone than file_get_contents/fread (remember the proxy issue with ssl...).

Between the all available libraries... I'd also say guzzle, but because it's heavily maintained and its community seems to be much bigger than others like HTTPFul (which would be a better option due to its simplicity, but the community thing throws me back).

**Comment by gtrias** [comment]
I think using Guzzle would be a good choice. It comes with a testing utilities to mock requests and responses. 
So let's use Guzzle :)
